name: Deploy Laravel to VPS

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 24700
          script: |
            cd /var/www/shopgame
            
            # Fetch latest changes
            git reset --hard
            git pull origin master
            
            # Install dependencies
            npm install
            
            # Build frontend
            npm run build
